# permissions for end users to edit metalstackfirewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metalstackfirewall-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalstackfirewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalstackfirewalls/status
  verbs:
  - get
